services:
  nginx:
    image: nginx:latest
    container_name: reverx
    restart: always
    extra_hosts:
      - "host.local:host-gateway"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./projects:/etc/nginx/sites-enabled:ro
      - ./nginx/init.sh:/entry-point/init.sh:ro
      - certs:/etc/nginx/certs
    command: bash /entry-point/init.sh
volumes:
  certs: